server:
  port: 9004

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost1:8801/eureka/,http://localhost2:8802/eureka/
  instance:
    instance-id: service4